### ISSUE TITLE
typehint instead of instanceof(\Redis) and exception?

### ISSUE THREAD

**Issue by HoffmannAndras** [jrschumacher/symfony-redis-session-handler#2]

**Comment by jrschumacher** [comment]
@NiGGa I'm not sure I follow your question.

**Comment by HoffmannAndras** [comment]
If you use typehint in the __construct() method, the if statement will be unnecessary.

**Comment by HoffmannAndras** [comment]
Like in Baachi's repo.

**Comment by jrschumacher** [comment]
I changed it for some reason, but feel free to send a pull request. Make sure to run the tests and/or fix the tests to work as needed. 

---

I think I might of changed it because I was planning on implementing [CRedis](https://github.com/colinmollenhour/credis), [PRedis](https://github.com/nrk/predis) as well as [PHP-Redis](https://github.com/phpredis/phpredis).

**Comment by HoffmannAndras** [comment]
No, thanks, my idea is available in the original repo.

Ryan Schumacher notifications@github.com ezt írta (időpont: 2015. máj.
11., H, 17:30):

**Comment by jrschumacher** [comment]
Okay cool. Closing this then.
